// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDZ6ntU8g-dMPjZ_SXPe4LQjPky0e0Tfo',
    appId: '1:230677489732:web:18e545e43a4a780b7cf411',
    messagingSenderId: '230677489732',
    projectId: 'sugarpals-20569',
    authDomain: 'sugarpals-20569.firebaseapp.com',
    storageBucket: 'sugarpals-20569.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDahfohLUIDUwZ-hoLaWGIDoXGCa6U_C-o',
    appId: '1:230677489732:android:bca3084aca8f6c0f7cf411',
    messagingSenderId: '230677489732',
    projectId: 'sugarpals-20569',
    storageBucket: 'sugarpals-20569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWdfyc0gtDp9lLAzM6bkIzbbBSnNKYki0',
    appId: '1:230677489732:ios:891a2c3a6c49f1d37cf411',
    messagingSenderId: '230677489732',
    projectId: 'sugarpals-20569',
    storageBucket: 'sugarpals-20569.firebasestorage.app',
    iosBundleId: 'com.example.sugarpals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWdfyc0gtDp9lLAzM6bkIzbbBSnNKYki0',
    appId: '1:230677489732:ios:891a2c3a6c49f1d37cf411',
    messagingSenderId: '230677489732',
    projectId: 'sugarpals-20569',
    storageBucket: 'sugarpals-20569.firebasestorage.app',
    iosBundleId: 'com.example.sugarpals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDZ6ntU8g-dMPjZ_SXPe4LQjPky0e0Tfo',
    appId: '1:230677489732:web:ddbd38c2378087717cf411',
    messagingSenderId: '230677489732',
    projectId: 'sugarpals-20569',
    authDomain: 'sugarpals-20569.firebaseapp.com',
    storageBucket: 'sugarpals-20569.firebasestorage.app',
  );
}
